src/sections/Hero.astro

Se arregla un error tipográfico al colocar el ALT en la imagen de Lola Lolita del Hero.

fix(Hero): Corrige typo "ques" → "que es"

---

src/sections/Hero.astro

Description:
Implemented Tailwind CSS media query classes (md:) to adjust the layout for medium devices.
Duplicated class attributes to ensure consistent styling across mobile and desktop views.
Enhanced the overall visual experience and grid structure.

Update grid layout in Hero section for responsive design

---

.prettierignore
.prettierrc
.vscode/extensions.json
.vscode/settings.json
package.json
pnpm-lock.yaml

Add prettier, plugins, and config files to ensure consistent code style.

chore: add prettier config

---

src/layouts/Layout.astro
src/styles/global.css

Apply Scroll smooth for "bento menu" and change default de scroll css for pink scroll bar
https://github.com/user-attachments/assets/ada39009-766d-4673-bd04-6ee03ec602cb

Feat and Style: Scroll Smoth and fancy pink scroll bar

---

src/components/LeafletMap.astro

- Add CSS import at the top of the file
- Check if "leaflet-map" already exists
- Use "connectedCallback" instead of the constructor
- Use "const" instead of "var"
- Add destructuring

refactor: Improve LeafletMap component structure and style definitions

---

README.md

> [!NOTE]
> LICENSE link is commented until LICENSE.md be created

docs: copy main branch readme

---

pull_request_template.md

Se ha añadido una plantilla mejorada para las Pull Requests (PR) del proyecto, con el objetivo de estandarizar y facilitar la descripción de los cambios realizados.
Esta nueva plantilla proporciona una estructura clara y consistente para los desarrolladores al documentar sus PRs, mejorando la comunicación dentro del equipo.
---
- ✔️ ] Mejora de documentación
---
- [ ✔️] No
---
El objetivo es proporcionar una herramienta útil para los desarrolladores del equipo, mejorando la calidad de las descripciones de PR.
---
No es necesario realizar pruebas, ya que el cambio únicamente afecta al archivo de plantilla …

docs:  se añadio plantilla para los Pull Requests

---

src/layouts/Layout.astro

Cambio del atributo "lang" para especificar que el contenido es español.

style: Cambio idioma cabecera HTML

---

package-lock.json
package.json
src/components/core/Particles.astro
src/components/core/particles.glsl.js
src/pages/index.astro

Se añaden partículas de fondo usando [ogl](https://www.npmjs.com/package/ogl).
Se ha creado un componente en astro para crear un _background_ de partículas que responden al movimiento del ratón (o _touch_ en dispositivos móviles).  Está inspirado en este componente: [Particles](https://www.reactbits.dev/backgrounds/particles) en React haciendole un port a Astro como **_web component_** _because why not_ ¯\\\_(ツ)\_/¯. 
El componente se puede configurar con las _props_ del componente. Si se quiere se puede probar (reactivamente) en [aqui](https://www.reactbits.dev/backgrounds/particles).  Una vez, contento con la configuración se pueden modificar las propiedades en _index.astro_.
```astro
<Particles
backgroundColor="#000000"
particleColors={["#FFE5EC", "#FFC2D1", "#FFB3C6", "#FF8FAB", …
```

feat: Un poco de vidilla a ese background: Hello Particles! (en la v1)

---

src/layouts/Layout.astro

- Se añade: preload de la imagen del Hero
- Se elimina: font weight no utilizada (poppins/800)
---
---
---
Carga de la imagen del Hero antes de que sea visible para el usuario. Mejora la velocidad de carga y la experiencia del usuario.
---
---
---

feat: added preload image and removed unused font weight

---

src/sections/Map.astro

Se arregla en la versión móvil, para evitar que esté tan pegado.
---
---
---
Mejora visual en versiones móviles.
---
---
Antes 🛑 
Ahora 🟢 
---

Fix(Map): Margen móvil

---

src/layouts/Layout.astro

Se ha movido la clase scroll-smoth del tag body al tag html para que se aplique correctamente el scroll smoth behavior.
---
---
---
Tener un scroll suave al dar clic a los enlaces del menú
---
Dando clic a los elementos del menú y visualizar un scroll suave a las secciones en lugar de un salto repentino.
---
---

fix: Move scroll smoth to html tag

---

src/sections/Sponsors.astro

Se ha solucionado un problema con el import de los logos, que hacía que no aparecieran.
---
---
---
---
---
---

fix: import of the sponsor logos

---

src/components/Header.astro
src/sections/Gallery.astro

- Había un error de tipado en el componente del Header agregándole a una variable su tipo correspondiente
- En la navegacion mobile reemplace los colores junto a los hovers y textos para que tenga una mejor vista
- Por ultimo agregue un blur al fondo del dialog de una imagen de la galeria
---
---
---
---
---
> Navegacion en web mobile:
> Visualización del blur:
---
Poner enlaces necesarios aquí, si no hay poner:

fix & feat: correction type variable dialogElement, replace text color and fixxed colors header mobile

---

.gitignore
src/sections/Hero.astro

Se ha añadido una plantilla mejorada para las Pull Requests (PR) del proyecto, con el objetivo de estandarizar y facilitar la descripción de los cambios realizados.
Esta nueva plantilla proporciona una estructura clara y consistente para los desarrolladores al documentar sus PRs, mejorando la comunicación dentro del equipo. En esta parte se describirá lo que se ha hecho.
---
- [X ] Corrección de errores (cambio no disruptivo que soluciona un problema)
---
- [X ] No
---
Ha cambiado el blur en la imagen princpal en el Hero.astro
---
No es necesario probarlo solo es una mejora de UI
---
Antes
Después
Es un cambio …

remove some blur effect to improve the ui

---

src/sections/FAQ.astro
src/sections/Footer.astro
src/sections/Hero.astro
src/sections/Map.astro
src/sections/Tickets.astro

1. Correcciones ortográficas y gramaticales.
2. Agregué `transition hover:scale-120` a los íconos sociales del footer.
---
---
---
---
No es necesario realizar pruebas, pues que el cambio no afecta a las funcionalidades del producto.
---
1. Correcciones ortográficas y gramaticales.
ANTES
DESPUÉS
2. Agregué `transition hover:scale-120` a los íconos sociales del footer.
---

fix: spelling errors and footer icons

---

src/sections/FAQ.astro

Se ha añadido una plantilla mejorada para las Pull Requests (PR) del proyecto, con el objetivo de estandarizar y facilitar la descripción de los cambios realizados.
Esta nueva plantilla proporciona una estructura clara y consistente para los desarrolladores al documentar sus PRs, mejorando la comunicación dentro del equipo. En esta parte se describirá lo que se ha hecho.
---
---
---
No afecta al comportamiento del producto final. 
---
No es necesario realizar pruebas

fix: corregir error tipográfico en la sección FAQ

---

src/components/LeafletMap.astro

---
---
Los botones del mapa se ven mejor
---
| Antes | Después | 
| - | - | 
| ![buttons-before](https://github.com/user-attachments/assets/a2f993b4-00c7-48e7-a095-5ffee8c909f7) | ![buttons-after](https://github.com/user-attachments/assets/69b44fbf-b442-431a-b926-7671fa6e5f84) | 
| Antes | Después | 
| - | - | 
| ![buttons-hover-before](https://github.com/user-attachments/assets/6903f983-d906-44ea-b9af-50366ec0e53b) | ![buttons-hover-after](https://github.com/user-attachments/assets/d6f59224-4d28-427e-876a-769455bc22c6) |

Fix estilo de los botones del mapa

---

src/sections/FAQ.astro

Se centran la imagen y el título de preguntas frecuentes en su versión móvil, y se agrega una separación
**Arregla:** *(En móvil no se veía centrado)*
---
- [ x ] Mejora visual.
---
- [ x ] No
---
Por ejemplo: 
Sólo afecta el estilo.
El objetivo es proporcionar una herramienta útil para los desarrolladores del equipo, mejorando la calidad de las descripciones de PR.
---
Por ejemplo: 
---
---
Poner enlaces necesarios aquí, si no hay poner:

Se centran la imagen y el título de preguntas frecuentes en su versión móvil, y se agrega una separación

---

src/components/Header.astro

Se ha añadido los nuevos colores al menú y se elimino el error del linter con respecto al mobileMenu **as HTMLDialogElement**
---
---
---
---
---
---

fix: update background-color and color on mobile version

---

src/sections/Gallery.astro

Se ha arreglado el cierre de las imágenes con ESC.
Se ha bloqueado el scroll cuando tienes una imagen abierta
---
---
---
---
---
---

fix: added transition with ESC and scroll when an img is open

---

src/sections/Gallery.astro

Se ha corregido la rotación de la imagen al entrar en una galería.
---
---
---
---

fix: fix image rotate

---

src/sections/Hero.astro

Se ha corregido un error tipográfico en la sección de Invitados Principales.
**Arregla:** *(No aplica)*
---
---
---
No afecta al comportamiento del producto final, solo es una palabra mal escrita.
---
---
---

fix(Hero): Correct typo in guest discovery text

---

src/sections/Hero.astro

Se ha añadido un resaltado del tiempo de duración y la experiencia del evento atravez de una animacion de gradiente y pequeñas estrellas aleatorias que aparecen y desaparecen q resaltan dichos puntos.
---
---
---
El objetivo es proporcionar una herramienta útil para los desarrolladores del equipo, mejorando la calidad de las descripciones de PR.
---
---
[letteranimation.webm](https://github.com/user-attachments/assets/99ddd3b0-2f98-407d-9ee8-4a18725f7f09)
---

fix: Resaltado del tiempo de duracion del evento and fixed conflic

---

src/sections/Footer.astro

Se ha añadido animación en el logo del footer, como el que tiene el Hero.
---
---
---
---
Por ejemplo: 
---

feat: add animation in the footer logo, as in the hero

---

package-lock.json
src/components/Header.astro
src/layouts/Layout.astro
src/sections/Footer.astro

**Arregla:** *Fallos en estilos css y elementos del footer y cambios en link del header
---
---
- [X ] No
---
---
---
---

-Fix: header link footer and layout issues

---

src/sections/Tickets.astro

Se ha agregado separación en el contenido del párrafo "Próximamente disponibles". También se ha removido color en el icon (redundante).
---
---
---

style: Próximamente disponibles, general text color and content separation

---

src/sections/Gallery.astro

Se ha arreglado el problema de desplazamiento de la página cuando se presionan las teclas de flecha (Izquierda/Derecha) en la galería, al mismo tiempo que se ha añadido soporte para las teclas A y D.
---
---
---
Las teclas de flecha y las teclas "A" y "D" deben funcionar para cambiar entre imágenes y el cambio de imágenes con flechas debe funcionar sin afectar el desplazamiento de la página.
---
Probar la funcionalidad de navegación en la galería al presionar las teclas de flecha (Izquierda/Derecha) o las teclas A y D. Verificar que la página no se desplace al presionar estas teclas.

 Fix arrow key scrolling & add support for "A" and "D" keys in lightbox

---

src/sections/FAQ.astro
src/sections/Hero.astro
src/styles/global.css

Se ha añadido un efecto de hover para el card de la sección FAQ, ademas que al hacer hover se cambia momentaneamente el background de la sección. se dejo comentada la imagen y se propuso la misma pero sin el efecto de fondo(rosado).  ademas que se propone dos videos con los comportamientos, para elegir el adecuado. si se acepta el PR.
---
---
---
El objetivo es proporcionar una herramienta útil para los desarrolladores del equipo, mejorando la calidad de las descripciones de PR.
---
---
[Grabación de pantalla 2025-03-17 a la(s) …

feact: Hover Effect on Card en la sección FAQ  

---

src/sections/Gallery.astro

Se ha añadido una animación se water al titulo de la galería.
---
---
---
---

feat: add water animation on gallery title

---

src/sections/FAQ.astro

Se ha ajustado el padding del contenedor de las preguntas frecuentes para que coincida con la imagen.
---
---
---
---
---

feat: Adjust alignment of text with respect to the image

---

src/components/WaveSeparator.astro
src/sections/Sponsors.astro

- Se ha añadido una inanición al componente waveseparator.
- Se ha añadido waveseparator en la parte superior de los Patrocinadores.
---
---
---
---

Wave separator animation

---

src/sections/Hero.astro

Añadido signos de puntuación y arreglado espacio en Hero.
---
---
---
---
No es necesario realizar pruebas, ya que el cambio únicamente afecta a 2 textos del Hero y no a funcionalidades del producto.
---
---

fix: text formatting

---

src/components/StarryBackground.astro
src/sections/Hero.astro
src/sections/Map.astro

- Se han añadido padding a las secciones donde no había padding, así en mobile se ve bien.
- Se ha arreglado el overflow que generaba el componente StarryBackground
---
---
---
---

Fix mobile padding

---

src/components/Sponsor.astro
src/styles/global.css

Se ha añadido un efecto shiny infinito sobre los sponsors.
---
---
---
---
---
https://github.com/user-attachments/assets/77185422-7ead-404a-a8a9-7e1abca5cfe0
---

style: add shiny animation effect to sponsor component

---

src/components/Header.astro

Se han cambiado los colores del botón de comprar entradas en el Header cuando está en end state para mejorar el contraste.
---
---
---
---
---
---

feat: improve contrast buy button

---

src/components/Marquee.astro

Se ha ajustado el tamaño del texto en el componente Marquee en pantallas pequeñas.
---
---
---
---
---
Antes:
Después:
---

feat: make marquee text size responsive on small screens

---

src/pages/404.astro

Se ha añadido página de error 404
---
---
---
Cuando un usuario accede a una página inexistente, se mostrará la nueva página de error 404 
---
---
---

feat: add custom 404 page

---

src/sections/FAQ.astro

Se propone mejorar el diseño de la sección de "Preguntas frecuentes", para que sea más atractiva y entendible para el usuario, esto debido a que el texto no tenia un buen contraste y por ende no se lograba presenciar del todo bien. Cabe resaltar que también está adaptado para móviles. Puede no ser la vista definitiva, pero podría ser un buen material para futuras mejoras.
---
---
---
---
---
Antes:
Después:
---

feat: enhance FAQ section with new design elements and animations

---

src/sections/Info.astro
src/sections/Map.astro
src/sections/Tickets.astro

Se mejoró la accesibilidad y la coherencia visual en las secciones "Tickets" e "Info" para ofrecer una experiencia más clara y consistente al usuario.
---
- Se eliminó el texto redundante:
- Antes: `"Las entradas estarán disponibles próximamente. ¡Mantente atento!"`
- Ahora: `"Entradas próximamente disponibles"`
- Se actualizaron los colores para mejorar el contraste:
- Fondo: `bg-pink-100`
- Texto: `text-pink-900`
---
- Se ajustó el estilo de los botones para mantener consistencia con el resto de la interfaz:
- Se agregó un efecto `hover:scale-105` en vez de cambio de colores, y va con consistencia con el estilo de hover scale que ya está implementado en otros elementos.
- El gradiente se aclaró para mejorar la legibilidad:
- Antes: `from-[#ff0695]/90 to-[#ff0695]`
- Ahora: …

Style: Mejora de accesibilidad y estilo en Tickets/Info

---

src/sections/Info.astro

He arreglado mi PR anterior ajustando con valores personalizados la propiedad de _scroll-mt_ utilizando unidades en _rem_ para adaptarse a diferentes resoluciones  (escritorio, tablet y móvil) asegurando una mejor visualización del contenido.
**Arregla:** *No aplica*
---
---
---
El usuario podrá ver la sección de información de una mejor manera cuando haga click en la opción de Info del header.
---
Realizar la prueba desde escritorio, tablet o dispositivo móvil
---
Antes
https://github.com/user-attachments/assets/53ac5cd2-e898-4c79-9162-49c215024a67
Despues
https://github.com/user-attachments/assets/33a51c6e-c29c-451f-b054-d98eb111b895
---

Style: Fixed scroll behavior for the info section with custom values

---

src/components/SponsorsBar.astro

Se ha arreglado que el logo de DNKY no se viese en dispositivos pequeños.
---
---
---
---
---
Antes:
Después:
---

fix: DKNY not visible on smaller devices

---

src/components/BubbleBackground.astro

Se ha añadido una plantilla mejorada para las Pull Requests (PR) del proyecto, con el objetivo de estandarizar y facilitar la descripción de los cambios realizados.
Esta nueva plantilla proporciona una estructura clara y consistente para los desarrolladores al documentar sus PRs, mejorando la comunicación dentro del equipo. En esta parte se describirá lo que se ha hecho.
---
---
---
Afecta un component que es BubbleBackground
---
Se puede ver en la parte del mapa 
---
Antes 
https://github.com/user-attachments/assets/718a48fb-155c-4e89-98a5-42317eb22b8a
Después 
---
https://github.com/user-attachments/assets/57ebfb87-0317-4dd2-9a4c-de8e4109b8d4

Add animation effect to simulate a real bubble 

---

src/components/Marquee.astro
src/sections/Info.astro

Se han ajustado algunos valores de padding, margin y font size para mejorar el aspecto en dispositivos pequeños.
---
---
---
---
---
Antes:
<div style="display: flex; gap: 10px; align-items: center;">
</div>
Después:
<div style="display: flex; gap: 10px; align-items: center;">
</div>
---

feat: padding, margin and font size adjustments for better responsiveness

---

src/sections/Info.astro

Se ha ajustado el gap con las mismas propiedades de la otra card visualmente se nota muchísimo más detalles en las capturas de pantalla.
---
---
---
---
---
Antes:
Después:
---

Se ha ajustado el gap con las mismas propiedades de la otra card

---

src/components/BackToTop.astro

Se ha rediseñado el button q se modifica al hacer Hover por un Tooltip mediante la propiedad after
---
---
---
---
---
Antes
[antes.webm](https://github.com/user-attachments/assets/18d56a14-8504-4951-b144-86d19e206c36)
Después 
[despues.webm](https://github.com/user-attachments/assets/677940f1-e338-4abd-b117-ec31bf694149)
---
Poner enlaces necesarios aquí, si no hay poner:

change button BackToTop

---

package.json
pnpm-lock.yaml

Se ha actualizado la version de tailwindcss a la [4.1.3](https://tailwindcss.com/blog/tailwindcss-v4-1) que posee nuevas utilidades como text-shadow, mask, entre otros.
---
---

Update tailwindcss to 4.1.3

---

src/sections/Tickets.astro

Este PR simplifica el uso del componente `Marquee` al reemplazar una lista manual repetitiva de `"Entradas"` con `Array(8).fill("Entradas")`. 
El cambio mejora la legibilidad y mantenibilidad del código sin alterar el resultado visual.
---
- **Archivos modificados**:
- `src\sections\Tickets.astro` .
---
```astro
<Marquee content={Array(8).fill("Entradas")} />
```

♻️  refactor: Simplify Marquee content with Array.fill

---

src/components/WaveSeparator.astro
src/sections/Gallery.astro
src/sections/Map.astro

se ha acomodado las burbujas para que desaparescan en el borde the la ola animada
---
---
---
Ahora las burbujas desaparecen en el borde de la ola 
---
Se puede usar el inspector y cambiar la resolucion de la pantalla ya que las animaciones de olas son 2 svgs uno para mobile y otro para desktop
---
Antes
https://github.com/user-attachments/assets/18bf50c5-0740-4f9e-8bc6-f3b257f8dc03
Despues
https://github.com/user-attachments/assets/c371564d-568e-4114-b057-bcd4f2087d9a
---

fix: bubbles on wave animation

---

package.json
pnpm-lock.yaml

Update tailwindcss to the latest version
Se ha actualizado tailwind a la versión 4.1.4
**Arregla:** *Actualiza los paquetes*
---
---
---
Por ejemplo: 
No afecta al comportamiento del producto final significativamente.
---
No es necesario realizar pruebas, ya que es actualizar con pnpm.
---
---
https://www.npmjs.com/package/tailwindcss

Update tailwindcss to 4.1.4
