package.json
pnpm-lock.yaml

Multiples veces midu ha dejado en claro, lo recomendable que es eliminar las carets en el **package.json** para evitar bugs con futuras actualizaciones de dependencias.
Se uso `pnpm install` para actualizar las dependencias en **pnpm-lock.yaml**

Eliminacion de Carets en package.json y pnpm-lock.yaml

---

src/sections/Tickets.astro

Arreglar error con el width=110%, dejaba un espacio en la versión móvil en las demás secciones.
Antes 🔴 
Ahora 🟢

FIX(TICKET): ajustar contenedor

---

src/sections/Hero.astro

Agregué un ligero efecto de hover a cada ítem del grid, aumentando su tamaño en 1% con una suave transición.
> No añadí el `cursor-pointer` para evitar redundancia en caso de que los demás ítems también tengan enlaces.

feat: add hover scale and transition

---

src/components/LeafletMap.astro
src/sections/Map.astro

- remove `container` (id) prop. `L.map` is overloaded: `L.map` also accepts an HTMLElement, use `this` instead.
- remove `containerstyle` prop to set the size of the map.  Use tailwindcss classes instead in the parent element.
- remove `div` children use `this` instead.
- no need to verify if leaflet-map component is defined (`CyclomaticComplexity--;`).
- remove `window.L` and use `L` from import directly.

refactor: LeafletMap

---

src/sections/Hero.astro

En las secciones que se agregaron el mapa y los tickets les puse el fondo primario, que cogiera bien el stroke al texto de "Compra tus tickets", con la idea de que se vea mejor estéticamente  y mejore el responsivo.

fix: assigning text-stroke correctly and padding for responsive sections hero

---

src/components/LeafletMap.astro

> [!IMPORTANT]
> in order to have a custom tile color we need a tile server that allows change tile colors on demand: google maps, mapbox, etc. have but the usage of them api costs money.  Openstreetmaps doesn't have this feature.  
We have some options:
- Use another public free tile provider.  There is a preview demo in github: https://leaflet-extras.github.io/leaflet-providers/preview/ (i did not found a pinkish tile server...)
- <strike>Create a custom provider tile server...</strike> https://openmaptiles.org/
- 🦄 **_Hack the color a little bit via css_** 🦄
This approach can solve with limitations by aplying a color filter via css.
Before:
After:

feat: tile color change without changing the tile server

---

src/components/Header.astro

- Solucionado el problema de cerrar el menú al hacer click sobre uno de los enlaces.
- También se añadió una animación al abrir y cerrar el menú.

fix: fix Close mobile menu on click

---

CONTRIBUTING.md
README.md

Moved part of the Contributing section from the README to a separate CONTRIBUTING.md file.
Added a Colaboradores section to acknowledge contributors.
The new Contributing guide is based on the Velada README and the previous README of this project.
📸 Screenshots:

ADD Contributing and colaboradores on readme 

---

src/components/Header.astro
src/sections/Hero.astro

Se ha añadido animaciones al hacer hover sobre los botones de abrir y cerrar menú, también se ha movido el ID del section ifo dentro del bento grid.
---
---
---
---
Haciendo hover sobre los botones de abrir y cerrar menú y dándole click a INFO.
---
---

Feat: add hove on open and close menu and move info id into bento grid 

---

src/sections/Tickets.astro

Se ha modificado las tarjetas de venta de entradas: 
- Ahora aparecen los 2 días del evento como jornadas únicas, eliminando los turnos de mañana y tarde
- Se añade icono de ticket en el botón de "Comprar entrada"
---
---
---
---
No es necesario realizar pruebas, ya que el cambio únicamente afecta a la apariencia de las tarjetas de compra de entradas.
---
---

feat: updated ticket sale cards

---

src/sections/Hero.astro

Se ha eliminado el `div` que actuaba como fondo (`<div class="absolute inset-px rounded-lg bg-white lg:rounded-tr-[2rem]"></div>`) y se ha trasladado la propiedad `bg-white` al `div` hermano siguiente. Este cambio simplifica la estructura del código y mantiene el mismo estilo visual, optimizando el uso de clases y evitando elementos innecesarios.
El `div` eliminado no parecía tener una funcionalidad adicional más allá de actuar como fondo, por lo que su eliminación no afecta al comportamiento del componente. Al mover la propiedad `bg-white` al `div` contenedor, se reduce la complejidad del código y se mejora su mantenibilidad.
- **Visual:** No hay cambios visuales, ya que el fondo blanco y los bordes redondeados se mantienen.
- **Funcional:** No se esperan impactos en la funcionalidad del …

Refactor: Refactorización del componente Hero: eliminación de divs absolutos

---

src/sections/Gallery.astro

Se han corregido varios errores en el sistema de lightbox de la galería de imágenes:
- Se corrigió un error tipográfico en el atributo `transition` del lightbox.
- Se agregó una validación para `lightBoxImg` antes de asignarle `src`, evitando errores en la consola.
**Arregla:** No hay un issue asociado.
---
---
---
- El lightbox ya no tiene un error tipográfico en el atributo `transition`.
- Se evita un posible error cuando `lightBoxImg` es `null` o `undefined`.
---
1. Abrir la galería de imágenes y hacer clic en una imagen para abrir el lightbox.
2. Verificar que la imagen se carga correctamente sin errores en la consola.
---
---

fix: correct typo in transition and validate lightBoxImg

---

src/components/Header.astro

Se elimina `hover:text:primary` del hamburger icon
---
---
---
Al hacer hover en el hamburger icon éste no desaparece.

Fix: Hamburger icon desaparece al hacer hover

---

src/components/WaveSeparator.astro
src/sections/Gallery.astro

Siguiendo la línea de @restoker en su #90 se añaden unas olas en la galería.
---
---
---
| Antes | Despues |
| - | - |
| ![image](https://github.com/user-attachments/assets/91ada6b1-2a94-4bba-8492-bba4ce3ed4db) | ![image](https://github.com/user-attachments/assets/cd8736f5-f6b6-4f09-819c-293dec620e79) | 
| ![image](https://github.com/user-attachments/assets/e2ffa3b7-ba80-484b-bca5-9791cd28636e) | ![image](https://github.com/user-attachments/assets/84d86d27-0220-4d3a-887c-f65394445653) |

feat: add WaveSeparator on Gallery

---

src/sections/Gallery.astro

Se ha añadido la navegación con teclas de flecha (`←` y `→`) en la lightbox de la galería, permitiendo a los usuarios desplazarse entre imágenes sin necesidad de hacer clic manualmente.
Esto mejora la experiencia de usuario, proporcionando una interacción más fluida e intuitiva dentro de la galería.
**Arregla:** No aplica
---
---
---
Al abrir una imagen en la lightbox, los usuarios pueden usar las teclas de flecha izquierda (`←`) y derecha (`→`) para navegar entre las imágenes.
Esto mejora la accesibilidad y usabilidad de la galería.
---
1. Abrir la galería y seleccionar una imagen para abrir la lightbox.  
2. Usar la tecla `→` para pasar a la siguiente imagen.  
3. Usar la tecla `←` para volver a la imagen anterior.  
4. Verificar que la navegación con teclas funciona correctamente y sin …

feat: add arrow key navigation to gallery lightbox

---

src/consts/galleryImages.ts

Se han corregido múltiples errores tipográficos en los textos alternativos de las imágenes de la galería. Estas correcciones mejoran la claridad y precisión de las descripciones de las imágenes.
**Arregla:** No hay un issue asociado.
---
---
---
Los textos alternativos de la galería ahora están correctamente escritos, mejorando la accesibilidad y claridad para lectores de pantalla y SEO.
---
No es necesario realizar pruebas funcionales, ya que los cambios solo afectan los textos alternativos y no el comportamiento de la aplicación.
---
---

fix: corrected typos in gallery alt texts

---

src/sections/Sponsors.astro

Se ha añadido un **`waves separador`** en la parte inferior de la sección de **sponsor** y se ha cambiado el **`background`** de la sección para que siga el estilo de la sección **`gallery`**.
---
---
---
El cambio introduce un **separador en forma de waves** en la parte inferior de la sección **sponsor** y ajusta el **background** para mantener la coherencia con la sección **gallery**.
---
- Verificar que la sección **sponsor** ahora tiene un **separador en forma de waves** en la parte inferior.
- Confirmar que el **background** de la sección se ha actualizado para coincidir con el estilo de la sección **gallery**.
- Asegurar que los cambios no afectan la estructura ni el diseño general de la página.
---
-Antes
-Después …

feat: add waves separator and change background in sponsor section

---

src/sections/FAQ.astro

Se ha modificado el enlace al documento de responsabilidad para que se abra en una nueva pestaña del navegador.
Para ello, se ha añadido el atributo target="_blank" junto con rel="noopener noreferrer" para mejorar la experiencia del usuario y aplicar buenas prácticas de seguridad.
---
---
---
Al hacer clic en el enlace del documento de responsabilidad, este se abrirá en una nueva pestaña en lugar de la misma ventana, mejorando la navegación del usuario.
---
Hacer clic en el enlace del documento de responsabilidad en la sección de preguntas frecuentes.
Verificar que el documento se abre en una nueva pestaña.
---

improvement: make responsibility document link open in new tab

---

src/sections/Sponsors.astro

Arreglado el fondo azul de la sección de sponsors reescalándose al hacer scroll.
---
---
---
El fondo azul de la sección de sponsors mantiene su tamaño a pesar de la animación.
---
Hacer scroll cerca de la sección de sponsors.
---
Antes:
Después:
---

fix: sponsors' background is no longer getting scaled

---

src/sections/FAQ.astro

Cambio de estilo del hiperlink en la sección de FAQ para que sea igual que el de la sección de Map.
---
---
---
El hiperlink en la sección de FAQ en hover ahora se ve igual que el de la sección de Map.
---
Pasar el ratón por encima del hiperlink.
---
Antes:
Después:
---

fix: hyperlink hover on FAQ now matches the other

---

src/sections/Gallery.astro

Se ha añadido la funcionalidad de navegación con los botones de anterior y siguiente dentro del lightbox para permitir a los usuarios desplazarse entre las imágenes de la galería de manera más fluida. Estos botones se muestran y ocultan automáticamente según la posición de la imagen actual, mejorando la experiencia de usuario.
---
---
---
Ahora, los botones añadidos permiten navegar entre las imágenes de la galería dentro del lightbox. Los botones se ocultan cuando no hay más imágenes hacia la izquierda o derecha.
---
Abrir el lightbox al hacer clic en una imagen de la galería.
Verificar que los botones aparezcan y funcionen correctamente según la posición de la imagen.
Asegurarse de que los botones se oculten cuando no …

feat: add prev/next buttons to navigate through images in lightbox

---

src/components/StarryBackground.astro
src/sections/Gallery.astro
src/sections/Sponsors.astro

Se ha añadido un nuevo componente `StarryBackground` que genera un fondo con estrellas distribuidas aleatoriamente.  
Este componente ha sido integrado en las secciones de `sponsors` y `gallery` para mejorar la estética visual.  
---
---
---
El fondo de las secciones de patrocinadores y galería ahora tendrá estrellas pequeñas distribuidas aleatoriamente.  
Este cambio es puramente visual y no afecta a la funcionalidad del producto.
---
1. Ir a las secciones de patrocinadores y galería.
2. Verificar que el fondo tiene estrellas generadas de manera aleatoria.
3. Comprobar que las estrellas no se superponen entre sí.
4. Asegurarse de que el rendimiento de la página no se ve afectado.
---
Antes
- Sección `Sponsor`
- Sección …

feat: add StarryBackground component to sponsors and gallery sections

---

src/sections/FAQ.astro

Se ha modificado el estilo de la imagen en la sección FAQ para que no tenga efecto al hacer click y se ha cambiado el cursor.
---
---
---
La imagen de la sección FAQ ahora solo tiene efecto en hover.
---
Pasar el ratón por encima de la imagen.
---
Antes:
Después:
---

fix: image no longer has button behavior

---

src/sections/FAQ.astro

- Se ha actualizado el contraste del texto en las preguntas frecuentes (FAQ) para garantizar una mejor legibilidad cuando el fondo cambia a azul claro al pasar el cursor sobre la imagen. 
- Además, se han actualizado los colores del texto para todo el contenido de las FAQ, incluyendo encabezados, preguntas y respuestas.
---
---
---
Los textos en la sección de FAQ serán más legibles cuando el fondo cambie a azul claro, evitando problemas de contraste.
Este cambio mejora la accesibilidad sin afectar la funcionalidad del producto.
---
1. Ir a la sección de preguntas frecuentes (FAQ).
2. Pasar el cursor sobre las imágenes de las tarjetas.
3. Verificar que el texto sigue siendo legible cuando el fondo cambia a azul claro.
---
Antes:
Despues:
---
No …

fix: improve text readability on FAQ card hover state

---

src/sections/Gallery.astro

Reposicionado los botones para cambiar de imagen en la galería para que sean visibles y funcionales en pantallas más pequeñas.
---
---
---
Los botones para cambiar de imagen en la galería aparecen en pantallas más pequeñas que lg.
---
Cambiar resolución y comprobar que aparecen los botones.
---
---

fix: prev/next buttons on gallery not visible on smaller devices

---

src/components/Header.astro

Se ha implementado la funcionalidad que permite cerrar el menú móvil al hacer clic o tocar fuera de él.
---
---
---
Ahora el menú se cierra automáticamente cuando se interactúa con áreas fuera del menú, sin necesidad de usar el botón de cierre.
---
Hacer tap o click fuera del menú en móvil.
---
---

feat: add mobile menu close functionality when tapping outside

---

src/sections/Info.astro

Se ha añadido la propiedad scroll-mt a la sección de "Info" para ajustar el desplazamiento al hacer clic en la opción, evitando que la vista se desplace demasiado hacia abajo y asegurando una mejor visualización del contenido. Nota: Borre mi PR anterior ya que no ví que había hecho un cambio a la propiedad de gap.
**Arregla:** *No aplica*
---
---
---
El usuario podrá ver la sección de información de una mejor manera cuando haga click en la opción de Info del header.
---
Realizar la prueba desde escritorio o dispositivo móvil
---
Antes
https://github.com/user-attachments/assets/f42a18ba-bbfb-4f98-9cd9-10a0d7f473ba
Despues
https://github.com/user-attachments/assets/bf007e68-87ef-4764-877c-d4c26892695e
---

Style: Added scroll-mt property for the info section

---

src/sections/Footer.astro
src/sections/Hero.astro

Se ha cambiado el efecto de cambio de fondo en el logo para simular un efecto de ola con un SVG, tanto en el Footer como en el Hero.
---
---
---
Por ejemplo: 
---
---
Antes:
https://github.com/user-attachments/assets/b457e99d-c18a-4ffa-8fc0-59b7b7aa94e0
Después:
https://github.com/user-attachments/assets/6efe18b4-71ff-4953-b07e-ced4a9f17b66
---

feat: replace logo background effect with SVG elements in Footer and Hero sections

---

src/components/Header.astro

Se ha corregido la transición del backdrop que se activa al abrir el sidemenu en móviles, haciendo que no desaparezca repentinamente sino con una transición.
---
---
---
Por ejemplo: 
---
Por ejemplo: 
No es necesario realizar pruebas
---
**Antes:**
https://github.com/user-attachments/assets/78235245-6da7-4be7-b7e2-d88a777becd8
**Después:**
https://github.com/user-attachments/assets/c54d6060-9781-4108-9e88-c4e556866163
---

fix: se corrige la transición del backdrop al accionar el nav

---

src/components/Header.astro
src/sections/Hero.astro

Se ha quitado un flex-1 para que el botón de comprar tickets quepa bien en el Header en dispositivos pequeños.
---
---
---
---
---
Antes:
Después:
---

fix: buy button now fits on small devices Header

---

src/components/Marquee.astro
src/sections/Tickets.astro

Se ajustó el banner de entradas para mejorar su presencia visual y el contraste con el fondo.
---
- Se aumentó el ancho de `110%` a `120%`
- Se incrementó el padding vertical de `py-2` a `py-8`
- El color del texto cambió de blanco (`text-white`) a azul `#383acf`, aplicado al título "Entradas" y los puntos separadores (`·`)
---
El banner ahora es más prominente, con mayor altura y un color que mejora la legibilidad sobre el fondo rosa claro.
Antes
Después

Style: Banner Marque Tweak

---

src/sections/Footer.astro

Se eliminó el texto duplicado "Lola Lolita Land" en el footer, ya que el logotipo ya contiene esa información visualmente. 
---
- Eliminado el texto plano "Lola Lolita Land" en el **footer**
- Añadido `role="img"` al SVG para mejorar la semántica y accesibilidad
- Añadido `<title>Lola Lolita Land</title>` dentro del SVG para que lectores de pantalla puedan interpretarlo correctamente
Antes
Después

Fix Duplicado en el Footer

---

src/sections/Gallery.astro

Se ha ajustado el tamaño de la fuente del título de la galería para evitar que en dispositivos móviles se produzca un salto de línea no deseado. Esto garantiza que la animación mantenga su fluidez y se visualice correctamente sin interrupciones.
**Arregla:** No hay issue asociado.
---
---
---
El título de la galería se mostrará correctamente en todas las pantallas sin dividirse en múltiples líneas en dispositivos móviles. Esto permite que la animación conserve su efecto de onda sin cortes o desajustes.
---
Se puede comprobar visualmente en dispositivos móviles o utilizando las herramientas de desarrollo del navegador para simular distintos tamaños de pantalla.
---
- Antes
https://github.com/user-attachments/assets/bedb96d9-8efe-4483-bb95-cf8df197 …

Fix: Prevent gallery title line break on mobile to preserve animation

---

src/sections/Gallery.astro

Se ha modificado la galería de fotos del año pasado para dispositivos móviles, haciendo que ahora se muestre un carrusel de las imágenes. Esto ayuda a que la página no tenga un scroll tan largo si se quiere llegar hasta abajo.
---
---
---
---
No es necesario realizar pruebas
---
Antes:
https://github.com/user-attachments/assets/b2d1f0fe-8ad7-48ee-9be3-982acf4e3799
Después:
https://github.com/user-attachments/assets/bca8fc29-b0bf-4d73-a239-2ba499d8926f
---

feat: Se adapta la galería para mostrar un slider en la versión móvil

---

src/sections/Gallery.astro

Se ha añadido el sufijo "slider" al thumb de las imágenes del slider en la galería para evitar errores de identificación.
---
---
---
Abrir imágenes de la galería y que al cerrarlas sigan en la lista de imágenes.
---
---
[antes.webm](https://github.com/user-attachments/assets/9d61531e-56c0-48dc-a3bc-4105fae84bee)
[despues.webm](https://github.com/user-attachments/assets/6c66a239-ce3d-49f9-b120-4a7bec891992)
---

fix: gallery images disappearing on pc

---

src/components/Header.astro

El mobile-menu ocupaba toda la pantalla en formato móvil, impidiendo visualizar el fondo y la información. Con este ajuste, ahora solo ocupa la parte superior, mejorando la experiencia visual al permitir tanto ver el fondo como el desplegable correctamente.

Actualización de Header.astro

---

src/components/BackToTop.astro

- Este PR realiza un refactor en la lógica de visibilidad del botón BackToTop, mejorando su legibilidad y mantenimiento.
Además, se ajusta dinámicamente el estilo del cursor (cursor-pointer / cursor-default) según si el botón está visible o no, evitando efectos de interacción innecesarios cuando el botón está oculto.
---
---
- Cuando está visible, el botón tiene el estilo cursor-pointer para indicar que es interactivo.
- Cuando está oculto (opacity-0), el cursor cambia a cursor-default, evitando confusión o efectos de interacción innecesarios.
- La lógica es más clara y modular, facilitando futuros ajustes o mejoras.
---
https://github.com/user-attachments/assets/39002630-e734-457c-b66f-36b78bfa7c7d …

✨ feature: Improve BackToTop button visibility

---

src/components/Header.astro
src/components/HeaderLink.astro

- Este PR añade el componente `HeaderLink` para la navegación en el encabezado. Incluye soporte para estilos específicos de `MOBILE` y `DESKTOP`, una prop opcional `extraClasses` para personalización.
---
- **Creación de `HeaderLink.astro`**:
- Nuevo componente para enlaces de navegación.
- Usa la prop `device` para alternar entre estilos `MOBILE` y `DESKTOP`.
- Incluye la prop opcional `extraClasses` para añadir clases CSS personalizadas.
- **Archivos añadidos**:
- `src/components/HeaderLink.astro`: Componente creado.
---
Necesitábamos un componente reutilizable y flexible para los enlaces del encabezado, con estilos adaptados a dispositivos y soporte para personalización. `HeaderLink` llena este propósito.
---
A continuación, ejemplos de cómo usar `HeaderLink` en diferentes casos: …

✨ feature: Create HeaderLink component for header refactor
